@startuml
skinparam state {
    BackgroundColor PapayaWhip
    BorderColor DarkSlateGray
}

state luaParser {
  state "Lua AST" as luaast
  state "Lua Source Code" as luasource

  luasource -> luaast
}

state Converter #Lavender {
  state "Lua AST" as luaast_
  state "Visit AST Node" as visit #Lavender {
    state "Map Types" as types #Lavender
    state "Handle Scopes" as scopes #Lavender
    state "Evalue Expression" as evalue #Lavender
    state "Add to Python AST" as add #Lavender
     scopes --> types
     scopes --> evalue
     evalue --> add
     types --> add
  }
  state "Python AST" as pyast_
  luaast_ -> visit
  visit -> pyast_
}
  

state Unparser {
  state "Python AST" as pyast
  state "Python Source Code" as pycode

  pyast -> pycode
}

state Execute #line.dashed;line.bold; {

}

[*] -> luaParser 
luaParser -[#salmon,thickness=7]> Converter
Converter -[#salmon,thickness=7]> Unparser
Converter -[#salmon,dashed,thickness=7]> Execute
Unparser --[hidden]> Execute
' Execute -> [*]

note bottom of luaParser
Already available
end note


note top of Unparser
Already available
end note

note bottom of Converter #LavenderBlush
<b>Need Developing</b> (Not Finished)
end note

@enduml